messages:
  response:
    start: "Добрий день!"
    unknown_command: "Я не знаю такої команди :("
    description: "Надішліть мені номери першої та останньої сторінок\nНаприклад 1 55\nВикористовуючи '+' я автоматично визначу номер останньої сторінки\n1+4 => 1 16"
  error:
    default: "¯\_(ツ)_/¯"